package com.apptolast.familyfilmapp.ui.theme

import androidx.compose.ui.graphics.Color

// Fliksy dark cinema palette: near-black foundations with controlled violet/magenta accents.
val primaryDark = Color(0xFF7C3BFF)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF2A155F)
val onPrimaryContainerDark = Color(0xFFE9DDFF)
val secondaryDark = Color(0xFFD946EF)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFF4A1557)
val onSecondaryContainerDark = Color(0xFFFFD6FA)
val tertiaryDark = Color(0xFFFF4F8B)
val onTertiaryDark = Color(0xFFFFFFFF)
val tertiaryContainerDark = Color(0xFF5C1430)
val onTertiaryContainerDark = Color(0xFFFFD9E5)
val errorDark = Color(0xFFFF6B7A)
val onErrorDark = Color(0xFF2E0007)
val errorContainerDark = Color(0xFF5C111A)
val onErrorContainerDark = Color(0xFFFFD9DE)
val backgroundDark = Color(0xFF07080F)
val onBackgroundDark = Color(0xFFF4F3FA)
val surfaceDark = Color(0xFF0D0E16)
val onSurfaceDark = Color(0xFFF4F3FA)
val surfaceVariantDark = Color(0xFF242538)
val onSurfaceVariantDark = Color(0xFFB8B5C8)
val outlineDark = Color(0xFF3B3D51)
val outlineVariantDark = Color(0xFF252738)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF4F3FA)
val inverseOnSurfaceDark = Color(0xFF171821)
val inversePrimaryDark = Color(0xFF5B21E6)
val surfaceDimDark = Color(0xFF07080F)
val surfaceBrightDark = Color(0xFF2B2D3E)
val surfaceContainerLowestDark = Color(0xFF05060B)
val surfaceContainerLowDark = Color(0xFF10111B)
val surfaceContainerDark = Color(0xFF151623)
val surfaceContainerHighDark = Color(0xFF1B1C2A)
val surfaceContainerHighestDark = Color(0xFF242538)

// Domain indicators that must stay instantly readable on the dark surface.
val greenAgeMovie = Color(0xFF32D583)
val redAgeMovie = Color(0xFFFF4F8B)
